..  |ACC|       replace:: Austin Community College
..  _ACC:       http://www.austincc.edu
..  _Arduino:   http://www.arduino.cc/
..  |CCC|       replace:: Carbon Copy Cloner
..  _CCC:       http://www.bombich.com/
..  _Git:       http://git-scm.com/
..  _GitHub:    http://github.com/
..  _HomeBrew:  http://brew.sh/
..  _MongoDB:   http://www.mongodb.org/
..  _OpenSCAD:  http://www.openscad.org/
..  _PovRay:    http://www.povray.org/
..  _Puppet:    http://puppetlabs.com/
..  _Rackspace: http://www.rackspace.com
..  _Ruby:      https://www.ruby-lang.org/en/
..  _Slic3r:    http://slic3r.org/
..  _Sphinx:    http://sphinx-doc.org/
..  _Ubuntu:    http://www.ubuntu.com
..  _Vagrant:   http://www.vagrantup.com/ 
